# This file was generated by GoReleaser. DO NOT EDIT.
cask "shelltime" do
  version "0.1.88"

  on_macos do
    on_intel do
      sha256 "6ffc33949383ed4947b49f09a5ea7738aa6ffcf3691036ead2f9180358e70db9"
      url "https://github.com/shelltime/cli/releases/download/v#{version}/cli_Darwin_x86_64.zip"
    end
    on_arm do
      sha256 "9905662126717367f461af85f17e376861903a7b64e7c04b0cfe073f275d7248"
      url "https://github.com/shelltime/cli/releases/download/v#{version}/cli_Darwin_arm64.zip"
    end
  end

  name "shelltime"
  desc "Track and analyze your shell usage - ShellTime CLI"
  homepage "https://shelltime.xyz"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shelltime"
  binary "shelltime-daemon"

  # No zap stanza required

  caveats <<~EOS
    Get started with a single command:
      shelltime init

    Or set things up manually:
      shelltime auth
      shelltime hooks install
      shelltime daemon install

    Learn more at https://shelltime.xyz
  EOS
end
