# This file was generated by GoReleaser. DO NOT EDIT.
cask "shelltime" do
  version "0.1.90"

  on_macos do
    on_arm do
      sha256 "073dbf44bc3c975d3c7316e267d9659653b834bdc21f97be5bb032db94059fc6"
      url "https://github.com/shelltime/cli/releases/download/v#{version}/cli_Darwin_arm64.zip"
    end
    on_intel do
      sha256 "2a1b5085ea891b1b2e0331f502927839baffb1fea6093299619f0423a489b692"
      url "https://github.com/shelltime/cli/releases/download/v#{version}/cli_Darwin_x86_64.zip"
    end
  end

  name "shelltime"
  desc "Track and analyze your shell usage - ShellTime CLI"
  homepage "https://shelltime.xyz"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shelltime"
  binary "shelltime-daemon"

  # No zap stanza required

  caveats <<~EOS
    Get started with a single command:
      shelltime init

    Or set things up manually:
      shelltime auth
      shelltime hooks install
      shelltime daemon install

    Learn more at https://shelltime.xyz
  EOS
end
