# This file was generated by GoReleaser. DO NOT EDIT.
cask "shelltime" do
  version "0.1.93"

  on_macos do
    on_arm do
      sha256 "1a2f42c00f4a2bbea3abfd212c6fa00299f595b7ed66282e7ea5bf77aa836490"
      url "https://github.com/shelltime/cli/releases/download/v#{version}/cli_Darwin_arm64.zip"
    end
    on_intel do
      sha256 "725c17d3c2ab9755f84d2ff93e9aa633c3e4520fe4b426af8a7b2c2f529ade87"
      url "https://github.com/shelltime/cli/releases/download/v#{version}/cli_Darwin_x86_64.zip"
    end
  end

  name "shelltime"
  desc "Track and analyze your shell usage - ShellTime CLI"
  homepage "https://shelltime.xyz"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shelltime"
  binary "shelltime-daemon"

  # No zap stanza required

  caveats <<~EOS
    Get started with a single command:
      shelltime init

    Or set things up manually:
      shelltime auth
      shelltime hooks install
      shelltime daemon install

    Learn more at https://shelltime.xyz
  EOS
end
