# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shelltime < Formula
  desc "Track and analyze your shell usage - ShellTime CLI"
  homepage "https://shelltime.xyz"
  version "0.1.86"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shelltime/cli/releases/download/v0.1.86/cli_Darwin_x86_64.zip"
      sha256 "e1c3675fc4fdf508e0e6fbacebe508ccf2fd091a6bc19ac2dc4e3844c722cac4"

      define_method(:install) do
        bin.install "shelltime"
        bin.install "shelltime-daemon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shelltime/cli/releases/download/v0.1.86/cli_Darwin_arm64.zip"
      sha256 "74ddcd8e76f60e2d240cb4879990b1a74dba2716d89e5ccf60374a84bdb747eb"

      define_method(:install) do
        bin.install "shelltime"
        bin.install "shelltime-daemon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shelltime/cli/releases/download/v0.1.86/cli_Linux_x86_64.tar.gz"
      sha256 "3da4ba6415793986f430a4a0e7326eba96383267f03706008c8e7193efac652f"
      define_method(:install) do
        bin.install "shelltime"
        bin.install "shelltime-daemon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shelltime/cli/releases/download/v0.1.86/cli_Linux_arm64.tar.gz"
      sha256 "65a7ebfe905979174948a64ec211d8c37936ad0404d84ae3b5b90210a9ecea43"
      define_method(:install) do
        bin.install "shelltime"
        bin.install "shelltime-daemon"
      end
    end
  end

  def caveats
    <<~EOS
      Get started with a single command:
        shelltime init

      Or set things up manually:
        shelltime auth
        shelltime hooks install
        shelltime daemon install

      Learn more at https://shelltime.xyz
    EOS
  end

  test do
    system "#{bin}/shelltime", "--version"
  end
end
