# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shelltime < Formula
  desc "Track and analyze your shell usage - ShellTime CLI"
  homepage "https://shelltime.xyz"
  version "0.1.87"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shelltime/cli/releases/download/v0.1.87/cli_Darwin_x86_64.zip"
      sha256 "00cbf0dbcf9762be60187f777d24fb482dd8e3ce5645b098cbedd0026f196894"

      define_method(:install) do
        bin.install "shelltime"
        bin.install "shelltime-daemon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shelltime/cli/releases/download/v0.1.87/cli_Darwin_arm64.zip"
      sha256 "bb2bc711ea4f2a24507fa466059ef671c6e37dc488a8ca1a6f532cb31c7fc98a"

      define_method(:install) do
        bin.install "shelltime"
        bin.install "shelltime-daemon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shelltime/cli/releases/download/v0.1.87/cli_Linux_x86_64.tar.gz"
      sha256 "27affcec6b2ae9f47e7d29ecaabd2f8704d0805c27ad94a402cbcfc05acab530"
      define_method(:install) do
        bin.install "shelltime"
        bin.install "shelltime-daemon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shelltime/cli/releases/download/v0.1.87/cli_Linux_arm64.tar.gz"
      sha256 "297ab436c0dbbd2f3c8e7189828897b8855ea8774f03b319254de0b5678b5bb9"
      define_method(:install) do
        bin.install "shelltime"
        bin.install "shelltime-daemon"
      end
    end
  end

  def caveats
    <<~EOS
      Get started with a single command:
        shelltime init

      Or set things up manually:
        shelltime auth
        shelltime hooks install
        shelltime daemon install

      Learn more at https://shelltime.xyz
    EOS
  end

  test do
    system "#{bin}/shelltime", "--version"
  end
end
