# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shelltime < Formula
  desc "Track and analyze your shell usage - ShellTime CLI"
  homepage "https://shelltime.xyz"
  version "0.1.84"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shelltime/cli/releases/download/v0.1.84/cli_Darwin_x86_64.zip"
      sha256 "43d383a3fc99a247fc62442711e34b253480fbde1243cc7691e23c04baf56c43"

      define_method(:install) do
        bin.install "shelltime"
        bin.install "shelltime-daemon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shelltime/cli/releases/download/v0.1.84/cli_Darwin_arm64.zip"
      sha256 "71c892d9584b6b25cb32ec04cacec56a8862026db1339ca2c5c5188d337380d0"

      define_method(:install) do
        bin.install "shelltime"
        bin.install "shelltime-daemon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shelltime/cli/releases/download/v0.1.84/cli_Linux_x86_64.tar.gz"
      sha256 "23d9c21164b1e10daa24463372ccd230c1877245c09988f6655da72866f77456"
      define_method(:install) do
        bin.install "shelltime"
        bin.install "shelltime-daemon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shelltime/cli/releases/download/v0.1.84/cli_Linux_arm64.tar.gz"
      sha256 "8f0b5a43ee7212233e4849097d61ff25f98c7257df5c8b6b464b638544e9cfc1"
      define_method(:install) do
        bin.install "shelltime"
        bin.install "shelltime-daemon"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with ShellTime, run:
        shelltime init

      Or set up manually:
        shelltime auth
        shelltime hooks install
        shelltime daemon install

      For more info, visit https://shelltime.xyz
    EOS
  end

  test do
    system "#{bin}/shelltime", "--version"
  end
end
